package entity;

public enum EntityState {
	STANDING_NORTH, STANDING_EAST, STANDING_SOUTH, STANDING_WEST,
	JUMPING_NORTH, JUMPING_EAST, JUMPING_SOUTH, JUMPING_WEST,
	ATTACKING_NORTH, ATTACKING_EAST, ATTACKING_SOUTH, ATTACKING_WEST
}
